apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ssapp2
  name: dev-ssapp2
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev-ssapp2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/backend/base
    repoURL: https://github.com/keithchong/gitopskamv2d.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
